### ISSUE TITLE
backward.hpp: No such file or directory

### ISSUE THREAD

**Issue by ryanESX** [xuhao1/VINS-Fisheye#29]
I disable cuda and try to build on ubuntu 18.04. it has following error:
```
/catkin_ws/src/VINS-Fisheye/vins_estimator/src/rosNodeFisheye.cpp:5:10: fatal error: backward.hpp: No such file or directory
 #include <backward.hpp>
          ^~~~~~~~~~~~~~
compilation terminated.
/catkin_ws/src/VINS-Fisheye/vins_estimator/src/rosNodelet.cpp:7:10: fatal error: backward.hpp: No such file or directory
 #include <backward.hpp>
          ^~~~~~~~~~~~~~
```
But I did install  back libdw-dev. Is there any missing library I didn't install?

**Comment by xuhao1** [comment]
@ryanESX  it’s here
https://github.com/bombela/backward-cpp/blob/master/backward.hpp
download to your include path
